version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
      - node-modules_frontend:/app/node_modules

volumes:
  node-modules_frontend:
