version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
      - node-modules_frontend:/app/node_modules
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - node-modules_backend:/app/node_modules
    command: npm start

volumes:
  node-modules_frontend:
  node-modules_backend:
