version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8000:3000"
    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

volumes:
  node-modules:
